[package]
name = "hmm"
version = "0.1.0"
authors = ["Sam Rose <hello@samwho.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
chrono = "0.4.11"
directories = "2.0.2"
itertools = "0.9.0"
textwrap = { version = "0.11", features = ["term_size"] }
colored = "1.9"
confy = "0.3.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.1.0"
easy_reader = "0.5.0"
structopt = { version = "0.3", default-features = false }

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1

[[bin]]
name = "hmm"
path = "src/bin/hmm.rs"

[[bin]]
name = "hmmq"
path = "src/bin/hmmq.rs"