[package]
name = "hmm"
version = "0.1.0"
authors = ["Sam Rose <hello@samwho.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
chrono = "0.4.11"
dirs = "2.0.2"
itertools = "0.9.0"
textwrap = { version = "0.11", features = ["term_size"] }
colored = "1.9"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1